config/routes.rb
Todo::Application.routes.draw do
  resources :tarefas
  root :to => "tarefas#index"

end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tarefa }
      else
        format.html { render action: 'new' }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:tarefa, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tarefas/_form.html.erb
<%= form_for(@tarefa) do |f| %>
  <% if @tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% @tarefa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tarefa %><br>
    <%= f.text_field :tarefa %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editando tarefa</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tarefa %> |
<%= link_to 'Voltar', tarefas_path %>

app/views/tarefas/index.html.erb
<h1>Listando tarefas</h1>

<table>
  <thead>
    <tr>
      <th>Tarefa</th>
      <th>Descrição</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tarefas.each do |tarefa| %>
      <tr>
        <td><%= tarefa.tarefa %></td>
        <td><%= tarefa.descricao %></td>
        <td><%= link_to 'Show', tarefa %></td>
        <td><%= link_to 'Edit', edit_tarefa_path(tarefa) %></td>
        <td><%= link_to 'Destroy', tarefa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>Nova tarefa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tarefa:</strong>
  <%= @tarefa.tarefa %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @tarefa.descricao %>
</p>

<%= link_to 'Editar', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Voltar', tarefas_path %>